-- AlterTable
ALTER TABLE "novels" ADD COLUMN     "recommendation" TEXT,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "published_at" SET DATA TYPE TIMESTAMPTZ(6);
